### ISSUE TITLE
Too many open files (os error 24)

### ISSUE THREAD

**Issue by cornzzy** [neevek/rstun#7] opened 2024-11-26 16:18 UTC
Hi! rstunc fails after about 6 hours with the following errors and I need to restart it manually:
```
2024-11-26 13:31:57.282 [rstunc] [rstun::tcp::tcp_server:88] [E] tcp server failed, err: Too many open files (os error 24)
2024-11-26 13:31:57.282 [rstunc] [rstun::tcp::tcp_server:88] [E] tcp server failed, err: Too many open files (os error 24)
2024-11-26 13:31:57.282 [rstunc] [rstun::tcp::tcp_server:88] [E] tcp server failed, err: Too many open files (os error 24)
```

The setup is (two hop):
`100 clients` -> `server1 running rstunc` -> `server2 running rstund and shadowsocks`

I set the open files limit to 60000 from 1024 in `/etc/security/limits.conf` and rebooted but the issue persists. `ulimit -n` returns 60000.

I should mention this doesn't happen with wireguard (udp) setup.

**Comment by neevek** [comment] 2024-11-27 00:17
Hi, can you share the commands that you run rstund and rstunc with?

**Comment by cornzzy** [comment] 2024-11-27 02:52
`rstund --addr 0.0.0.0:443 --password password --cert /etc/letsencrypt/live/example.com/fullchain.pem --key /etc/letsencrypt/live/example.com/privkey.pem -l E`

`rstunc --mode OUT -a example.com:443 --password password --tcp-mapping 0.0.0.0:8443^2525 --dns 9.9.9.9 -l E`

So, I actually rebooted after the second time it happened and its been about 9 hours and it's running without error. I'll let you know if it fails today.

**Comment by neevek** [comment] 2024-11-27 13:56
Are you using the latest version 0.6.2?

**Comment by cornzzy** [comment] 2024-11-28 09:34
My bad, didn't check rstund logs. The too many open files error was there too so I increased it. Closing this as this issue can be resolved by increasing open files limit on both client and server side.

**Comment by neevek** [comment] 2024-11-28 09:49
For high concurrent connections, increasing open file limits is necessary, but 60000 is a lot :-)

**Comment by cornzzy** [comment] 2024-11-28 10:53
Oh no, it happened again but it took half a day this time:
```
2024-11-28 14:05:50.938 [rstunc] [rstun::tcp::tcp_tunnel:61] [E] failed to get peer_addr: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }
2024-11-28 14:06:08.229 [rstunc] [rstun::tcp::tcp_tunnel:61] [E] failed to get peer_addr: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }
2024-11-28 14:06:08.229 [rstunc] [rstun::tcp::tcp_tunnel:61] [E] failed to get peer_addr: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }
```
No errors on rstund.

**Comment by neevek** [comment] 2024-11-28 11:07
> Oh no, it happened again but it took half a day this time:
> ```
> 2024-11-28 14:05:50.938 [rstunc] [rstun::tcp::tcp_tunnel:61] [E] failed to get peer_addr: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }
> 2024-11-28 14:06:08.229 [rstunc] [rstun::tcp::tcp_tunnel:61] [E] failed to get peer_addr: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }
> 2024-11-28 14:06:08.229 [rstunc] [rstun::tcp::tcp_tunnel:61] [E] failed to get peer_addr: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }
> ```
> No errors on rstund.

> You may use `ls -l /proc/RSTUND_PID/fd I wc -l` to check if the server is hitting the open file limit.

And if possible try older versions, which will help me spot the bug.

**Comment by neevek** [comment] 2024-11-28 13:49
Try this new [release](https://github.com/neevek/rstun/releases/tag/release%2F0.6.3), I added some timeout for tcp read. 

The issue is related to too many open tcp streams, it could be your upstream (in your case the server listening on `2525`) is holding tcp connections unclosed or something like that.

**Comment by cornzzy** [comment] 2024-11-29 05:18
6.0.3 been going longer with no errors. But the speed seems quite low.  Does the change affect speed? Have 4 of this each second:
`
2024-11-28 20:19:12.575 [rstunc] [rstun::tcp::tcp_tunnel:109] [W] tcp stream timeout
`

**Comment by neevek** [comment] 2024-11-29 07:04
> 6.0.3 been going longer with no errors. But the speed seems quite low. Does the change affect speed?

Do you mean open file limit is still hit, only it takes longer to happen? The change shouldn't cause transfer speed though.

> Have 4 of this each second:
> `
> 2024-11-28 20:19:12.575 [rstunc] [rstun::tcp::tcp_tunnel:109] [W] tcp stream timeout
> `

Each second? Do you mean there are timeout errors constantly? This is quite unexpected, it means the upsteam is holding connections without sending data.

I will tweak the code a little bit later and may rollout a new release soon.

**Comment by cornzzy** [comment] 2024-11-29 08:53
It no longer disconnects. The open file usage is less 1000. Just lots of timeout warning.

**Comment by neevek** [comment] 2024-11-29 13:53
> It no longer disconnects. The open file usage is less 1000. Just lots of timeout warning.

Check out the [least release](https://github.com/neevek/rstun/releases/tag/release%2F0.6.4).

I adjusted the code related to timeout, this time if you see timeout warnings, it is expected, it means connections are being held for over 30 seconds without sending data from either side, and they will be closed in this case for the sake of not running out of file descriptors.

If you are see a lot of timeout warnings with the 0.6.4, you may need to check your upstream server or your clients, why are they holding connections without sending any data?

> 6.0.3 been going longer with no errors. But the speed seems quite low.

As for this one, you can benchmark the latest release against older version like 0.6.2.

**Comment by cornzzy** [comment] 2024-11-29 14:59
What does this mean?
![{EC4A1796-CABF-49A0-9DF9-070B2E894F90}](https://github.com/user-attachments/assets/744f918a-e943-42de-9faa-1b4361629f45)

**Comment by neevek** [comment] 2024-11-29 15:47
> What does this mean?
> ![{EC4A1796-CABF-49A0-9DF9-070B2E894F90}](https://github.com/user-attachments/assets/744f918a-e943-42de-9faa-1b4361629f45)
> 

I already explained in my previous comment. This may or may not be an issue, but it is not related to rstun itself.

**Closed** 2024-11-30 04:50 UTC
